<?php

namespace ContainerVnods1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LQiV2eiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LQiV2ei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LQiV2ei'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnnonceController::index' => ['privates', '.service_locator.KuAM0Ta', 'get_ServiceLocator_KuAM0TaService', true],
            'App\\Controller\\AvisController::delete' => ['privates', '.service_locator.s74uhdR', 'get_ServiceLocator_S74uhdRService', true],
            'App\\Controller\\AvisController::edit' => ['privates', '.service_locator.s74uhdR', 'get_ServiceLocator_S74uhdRService', true],
            'App\\Controller\\AvisController::index' => ['privates', '.service_locator.eeGHuji', 'get_ServiceLocator_EeGHujiService', true],
            'App\\Controller\\AvisController::new' => ['privates', '.service_locator._TtK.y8', 'get_ServiceLocator_TtK_Y8Service', true],
            'App\\Controller\\AvisController::show' => ['privates', '.service_locator.XxYNAyR', 'get_ServiceLocator_XxYNAyRService', true],
            'App\\Controller\\DefaultController::default' => ['privates', '.service_locator.KuAM0Ta', 'get_ServiceLocator_KuAM0TaService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AnnonceController:index' => ['privates', '.service_locator.KuAM0Ta', 'get_ServiceLocator_KuAM0TaService', true],
            'App\\Controller\\AvisController:delete' => ['privates', '.service_locator.s74uhdR', 'get_ServiceLocator_S74uhdRService', true],
            'App\\Controller\\AvisController:edit' => ['privates', '.service_locator.s74uhdR', 'get_ServiceLocator_S74uhdRService', true],
            'App\\Controller\\AvisController:index' => ['privates', '.service_locator.eeGHuji', 'get_ServiceLocator_EeGHujiService', true],
            'App\\Controller\\AvisController:new' => ['privates', '.service_locator._TtK.y8', 'get_ServiceLocator_TtK_Y8Service', true],
            'App\\Controller\\AvisController:show' => ['privates', '.service_locator.XxYNAyR', 'get_ServiceLocator_XxYNAyRService', true],
            'App\\Controller\\DefaultController:default' => ['privates', '.service_locator.KuAM0Ta', 'get_ServiceLocator_KuAM0TaService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AnnonceController::index' => '?',
            'App\\Controller\\AvisController::delete' => '?',
            'App\\Controller\\AvisController::edit' => '?',
            'App\\Controller\\AvisController::index' => '?',
            'App\\Controller\\AvisController::new' => '?',
            'App\\Controller\\AvisController::show' => '?',
            'App\\Controller\\DefaultController::default' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnnonceController:index' => '?',
            'App\\Controller\\AvisController:delete' => '?',
            'App\\Controller\\AvisController:edit' => '?',
            'App\\Controller\\AvisController:index' => '?',
            'App\\Controller\\AvisController:new' => '?',
            'App\\Controller\\AvisController:show' => '?',
            'App\\Controller\\DefaultController:default' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
