<?php

namespace ContainerVnods1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EeGHujiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eeGHuji' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eeGHuji'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'userTestRepository' => ['privates', 'App\\Repository\\UserTestRepository', 'getUserTestRepositoryService', true],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'userTestRepository' => 'App\\Repository\\UserTestRepository',
        ]);
    }
}
