<?php

namespace ContainerVnods1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvis2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.s74uhdR.App\Entity\Avis' shared service.
     *
     * @return \App\Entity\Avis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.s74uhdR": it references class "App\\Entity\\Avis" but no such service exists.');
    }
}
