<?php

namespace ContainerJEaMFko;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S74uhdRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s74uhdR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s74uhdR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'avi' => ['privates', '.errored..service_locator.s74uhdR.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.s74uhdR": it references class "App\\Entity\\Avis" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'avi' => 'App\\Entity\\Avis',
            'entityManager' => '?',
        ]);
    }
}
