<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnods1k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnods1k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnods1k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnods1k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVnods1k\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vnods1k',
    'container.build_id' => '036d03e9',
    'container.build_time' => 1698045620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnods1k');
